### ISSUE TITLE
Final report

### ISSUE THREAD

**Issue by tamasori** [Teaching-projects/SZE-MOSZE-2020-Pottyok#26]
@hegyhati Elkészültünk a videókkal és a report.md-vel.
Mergeltük is őket masterbe. 

- [report.md](https://github.com/Teaching-projects/SZE-MOSZE-2020-Pottyok/blob/master/report.md)

**Comment by oliverosz** [comment]
Szépen dolgoztatok, jár mindenkinek az 5-ös.
