### ISSUE TITLE
Conflict resolving in PR

### ISSUE THREAD

**Issue by tamasori** [Teaching-projects/SZE-MOSZE-2020-Pottyok#6]
@hegyhati @vizvezetek 
Olyan problémába akadtunk, hogy az én branchem, a levelup mergelésre került, és @balintxd branche, az attackspeed is elfogadásra került, azonban conflictok vannak. A megjelölt conflictokat gond nélkül tudjuk resolvoni, viszont van egy olyan baj, hogy a Player osztályban még nincs AttackSpeed-ről szó sehol. Szóval ha megoldunk minden conflictot, csak egy plusz committal tudnánk a kódot működőképesség tenni újra, hiszen bele kell raknunk, hogy a Player class átadja az AttackSpeedet az Entity-nek.

Viszinont a Player classt nem tudjuk szerkeszteni a Resolve Conflict menüpont alatt. A javító commitot hova pusholjuk? Vagy van erre valami egyértelmű megoldás?

**Comment by hegyhati** [comment]
Pont ez volt a cel. Amelyik most nyitva van, ha jol ertem, az attackspeed, az eloszor onmagaban legyen approve-olva. Ha ez megvan, akkor tessek resolve-olni a conflictokat, es ha ez is megvan, akkor @vizvezetek ujra review-zni fogja. REsolve-olni conflictot nem csak a gui-n kattintgatassal lehet, sot, nem is ott ajanlott. Tessek normalisan lokalisan merge-elni a mastert-t az attackspeed-be, feloldani a conflictokat a merge commit-ban, pusholni, majd kerni a review-t. De szerintem ez el volt mondva @oliverosz videojaban, hogy kell ilyet csinalni.
